export const DEPARTMENT = 'DEPARTMENT';
export const DEPARTMENT_CREATE = 'DEPARTMENT_CREATE';
export const DEPARTMENT_UPDATE = 'DEPARTMENT_UPDATE';
export const DEPARTMENT_DELETE = 'DEPARTMENT_DELETE';