/* eslint-disable react-refresh/only-export-components */
export * from './admin';
export * from './attendance';
export * from './dashboard';
export * from './faculty';
export * from './department';
export * from './level';
export * from './semester';
export * from './course';
export * from './student';