export const GET_CURRENT_SEMESTER = "GET_CURRENT_SEMESTER";

export const GET_LECTURER_FACULTIES = "GET_LECTURER_FACULTIES";

export const GET_LECTURER_DEPARTMENTS =
    "GET_LECTURER_DEPARTMENTS";

export const GET_LECTURER_LEVELS =
    "GET_LECTURER_LEVELS";

export const GET_AVAILABLE_LECTURER_COURSES =
    "GET_AVAILABLE_LECTURER_COURSES";

export const GET_MY_LECTURER_COURSES =
    "GET_MY_LECTURER_COURSES";

export const REGISTER_LECTURER_COURSES =
    "REGISTER_LECTURER_COURSES";

export const REMOVE_LECTURER_COURSE =
    "REMOVE_LECTURER_COURSE";