export const LECTURER_DASHBOARD = "LECTURER_DASHBOARD";
export const LECTURER_DASHBOARD_LOADING =
    "LECTURER_DASHBOARD_LOADING";
export const LECTURER_DASHBOARD_ERROR =
    "LECTURER_DASHBOARD_ERROR";