export const GET_ACTIVE_ATTENDANCE =
    "GET_ACTIVE_ATTENDANCE";

export const START_ATTENDANCE =
    "START_ATTENDANCE";

export const CLOSE_ATTENDANCE =
    "CLOSE_ATTENDANCE";

export const LECTURER_ATTENDANCE_LOADING =
    "LECTURER_ATTENDANCE_LOADING";

export const LECTURER_ATTENDANCE_ERROR =
    "LECTURER_ATTENDANCE_ERROR";